import glob, os, sys


configfile: "config.yaml"

include: "rules/chewie.smk"
include: "rules/milestone.smk"

rule all:
	input:
		sample_fasta = "data/"+config["aligner"]+"/"+"".join(config["samples"]["sample1"].split('_1')[0])+".fasta"